### PR TITLE
Make use of ES6 modules syntax

### PR DESCRIPTION
**Pull request by iamolivinius**
That's all I had to change.  I can compile your project with Typescript 2.0 and 1.8 without any compiler warnings/errors.

It's also possible to import individual functions like this: 

``` ts
import {getItem} from 'localforage'
```

### CODE REVIEW

**Comment by thgreasi** [comment]
Did you try running it?
TS compilation was working before as well, but I had runtime errors.
This kind of import is also used by nolanlawson/pouchdb-ionic-2-typescript-demo#1.

**Comment by thgreasi** [comment]
Also, the code that this PR proposes is exactly what I was trying to do in 9dde24d813fbaca1e2f699267be2eb1feba07daf but unfortunately I couldn't have it detect the appropriate type for the imported variable without explicit casting.

**Comment by iamolivinius** [comment]
I'd say it's working...I build it with `gulp build` and used `http-server` to serve it. 

screenshot from 2016-09-26 16-42-07

**Comment by thgreasi** [comment]
Ok, thanks for your collaboration.
I will try updating my ts packages and will report back.

**Comment by thgreasi** [comment]
Thanks. I will comment on LocalForage repo.

**Pull request merged**
